In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('данные.csv', sep=',')

In [9]:
mau = df['user_id'].nunique()
print(f"MAU (уникальные пользователи): {mau}")

MAU (уникальные пользователи): 7639

In [8]:
df.head()

         date                               user_id  view_adverts
0  2023-11-11  8c020470-8461-11ed-83d0-552e8cc749d6            13
1  2023-11-18  5875f070-7b92-11ee-a6fb-8b298e83f4f7            14
2  2023-11-29  3c2d27c0-4fd6-11eb-b89f-2ffb31b67dd6            21
3  2023-11-29  234a96d0-ad16-11ed-a2e6-793ddfeeba1f            23
4  2023-11-29  4d07c180-644f-11eb-879c-b7c02edf4f37            12

In [10]:
df['date'] = pd.to_datetime(df['date'])

In [12]:
dau = df.groupby('date')['user_id'].nunique()

In [13]:
print("DAU по дням:")
print(dau)

DAU по дням:
date
2023-11-01    623
2023-11-02    649
2023-11-03    573
2023-11-04    343
2023-11-05    350
2023-11-06    660
2023-11-07    629
2023-11-08    600
2023-11-09    661
2023-11-10    583
2023-11-11    354
2023-11-12    377
2023-11-13    646
2023-11-14    687
2023-11-15    690
2023-11-16    639
2023-11-17    585
2023-11-18    412
2023-11-19    378
2023-11-20    711
2023-11-21    651
2023-11-22    608
2023-11-23    632
2023-11-24    595
2023-11-25    366
2023-11-26    372
2023-11-27    589
2023-11-28    610
2023-11-29    621
2023-11-30    620
Name: user_id, dtype: int64

In [14]:
print(f"\nСреднее DAU за ноябрь: {dau.mean():.2f}")

Среднее DAU за ноябрь: 560.47

In [15]:
df = pd.read_csv('данные.csv', sep=None, engine='python')

In [17]:
first_orders = df.groupby('user_id')['date'].min().reset_index()
first_orders.columns = ['user_id', 'first_visit']

In [27]:
cohort_nov1 = first_orders[first_orders['first_visit'] == '2023-11-01']
cohort_users = cohort_nov1['user_id'].unique()
initial_count = len(cohort_users)

In [19]:
returned_day1 = df[(df['user_id'].isin(cohort_users)) & (df['date'] == '2023-11-02')]
returned_count = returned_day1['user_id'].nunique()

In [20]:
retention_d1 = (returned_count / initial_count) * 100

print(f"Пользователей пришло 1 ноября: {initial_count}")
print(f"Вернулось 2 ноября: {returned_count}")
print(f"Retention 1-го дня: {retention_d1:.2f}%")

Пользователей пришло 1 ноября: 623
Вернулось 2 ноября: 166
Retention 1-го дня: 26.65%

In [22]:
df = pd.read_csv('данные.csv', sep=None, engine='python')

In [23]:
total_users = df['user_id'].nunique()

In [24]:
users_with_views = df[df['view_adverts'] > 0]['user_id'].nunique()

In [25]:
conversion = (users_with_views / total_users) * 100

In [26]:
print(f"Всего пользователей в ноябре: {total_users}")
print(f"Пользователей, смотревших объявления: {users_with_views}")
print(f"Пользовательская конверсия: {conversion:.2f}%")

Всего пользователей в ноябре: 7639
Пользователей, смотревших объявления: 3538
Пользовательская конверсия: 46.31%

In [28]:
total_ad_views = df['view_adverts'].sum()

In [29]:
total_unique_users = df['user_id'].nunique()

In [30]:
average_views_per_user = total_ad_views / total_unique_users

In [31]:
print(f"Общее количество просмотров: {total_ad_views}")
print(f"Общее количество уникальных пользователей: {total_unique_users}")
print(f"Среднее количество просмотров на одного пользователя: {average_views_per_user:.2f}")

Общее количество просмотров: 21914
Общее количество уникальных пользователей: 7639
Среднее количество просмотров на одного пользователя: 2.87

In [33]:
total_users = 2000
promoters = 1200 
detractors = 500  
passives = 300

In [34]:
promoters_percent = (promoters / total_users) * 100
detractors_percent = (detractors / total_users) * 100

In [35]:
nps = promoters_percent - detractors_percent

In [36]:
print(f"Процент сторонников: {promoters_percent}%")
print(f"Процент критиков: {detractors_percent}%")
print(f"NPS (индекс лояльности): {nps}")

Процент сторонников: 60.0%
Процент критиков: 25.0%
NPS (индекс лояльности): 35.0

In [41]:
df_ab.head()

         date                               user_id  view_adverts
0  2023-11-11  8c020470-8461-11ed-83d0-552e8cc749d6            13
1  2023-11-18  5875f070-7b92-11ee-a6fb-8b298e83f4f7            14
2  2023-11-29  3c2d27c0-4fd6-11eb-b89f-2ffb31b67dd6            21
3  2023-11-29  234a96d0-ad16-11ed-a2e6-793ddfeeba1f            23
4  2023-11-29  4d07c180-644f-11eb-879c-b7c02edf4f37            12

In [43]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\admin\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\admin\anaconda3\lib\site-packages (from openpyxl) (2.0.0)

In [45]:
import pandas as pd

file_path = 'тест.xlsx'

df_audience = pd.read_excel(file_path, sheet_name=0)

df_ab = pd.read_excel(file_path, sheet_name=1)

df_third = pd.read_excel(file_path, sheet_name=2)

print("Колонки во второй вкладке:", df_ab.columns.tolist())

Колонки во второй вкладке: ['experiment_num', 'experiment_group', 'user_id', 'revenue']

In [46]:
import pandas as pd
from scipy import stats

for exp_num in df_ab['experiment_num'].unique():
    current_exp = df_ab[df_ab['experiment_num'] == exp_num]
    
    control = current_exp[current_exp['experiment_group'] == 'control']['revenue']
    test = current_exp[current_exp['experiment_group'] == 'test']['revenue']
    
    arpu_control = control.mean()
    arpu_test = test.mean()
    
    t_stat, p_val = stats.ttest_ind(control, test, equal_var=False)
    
    print(f"--- Эксперимент №{exp_num} ---")
    print(f"ARPU Контроль: {arpu_control:.2f}")
    print(f"ARPU Тест: {arpu_test:.2f}")
    print(f"p-value: {p_val:.4f}")
    
    if p_val < 0.05:
        print("Результат: СТАТИСТИЧЕСКИ ЗНАЧИМО. Разница есть.")
    else:
        print("Результат: Незначимо. Разница случайна.")
    print("\n")

--- Эксперимент №1 ---
ARPU Контроль: 722.46
ARPU Тест: 665.74
p-value: 0.6890
Результат: Незначимо. Разница случайна.


--- Эксперимент №2 ---
ARPU Контроль: 704.65
ARPU Тест: 332.93
p-value: 0.0011
Результат: СТАТИСТИЧЕСКИ ЗНАЧИМО. Разница есть.


--- Эксперимент №3 ---
ARPU Контроль: 663.21
ARPU Тест: 998.67
p-value: 0.0603
Результат: Незначимо. Разница случайна.

In [47]:
import pandas as pd

df_listers = pd.read_excel('тест.xlsx', sheet_name=2)

print(df_listers.columns)

Index(['user_id', 'date', 'cnt_adverts', 'age', 'cnt_contacts', 'revenue'], dtype='object')

In [48]:
df_listers = pd.read_excel('тест.xlsx', sheet_name=2)

total_revenue = df_listers['revenue'].sum()

unique_users = df_listers['user_id'].nunique()

arpu = total_revenue / unique_users

print(f"Общая выручка: {total_revenue:.2f}")
print(f"Уникальных пользователей: {unique_users}")
print(f"Средний доход на пользователя (ARPU): {arpu:.2f}")

Общая выручка: 4851.00
Уникальных пользователей: 31
Средний доход на пользователя (ARPU): 156.48

In [49]:
age_median = df_listers['age'].median()

print(f"Медиана возраста пользователей: {age_median}")

Медиана возраста пользователей: 28.0